import type { Metadata } from 'next'
import { League_Spartan } from 'next/font/google'
import '@/style/globals.css'

const leagueSpartan = League_Spartan({
	subsets: ['latin'],
	weight: ['500', '700'],
	variable: '--font-league-spartan'
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${leagueSpartan.variable}  antialiased`}>{children}</body>
		</html>
	)
}
